### ISSUE TITLE
All analyzers from assembly BlowinCleanCode failed to load: Unable to load one or more of the requested types.

### ISSUE THREAD

**Issue by Lukkian** [blowin/BlowinCleanCode#82]
All analyzers from assembly BlowinCleanCode failed to load: Unable to load one or more of the requested types. Could not load file or assembly 'Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

dotnet 6.0.101

**Comment by blowin** [comment]
What version of VS are you using? You are using VSIX extension or roslyn analyzer?

**Comment by luis-fss** [comment]
I'm using Jetbrains Rider.

**Comment by blowin** [comment]
check new version 2.5.7

**Comment by luis-fss** [comment]
Yes, everything working as expected, thanks.
